
override CLEW_3RDPARTY_PATH         	= ${CURDIR}/3rdparty
override CLEW_3RDPARTY_INSTALL_PATH	= ${CLEW_3RDPARTY_PATH}/install
override CLEW_LIBMAKEFILE_PATH      	= ${CLEW_3RDPARTY_PATH}/libmakefile

CLEW_MIMALLOC_ENABLE			?= y

subdir-y += \
	3rdparty \
	src \
	test

3rdparty_makeflags-y = \
	CLEW_LIBMAKEFILE_PATH=${CLEW_LIBMAKEFILE_PATH} \
	CLEW_3RDPARTY_PATH=${CLEW_3RDPARTY_PATH} \
	CLEW_3RDPARTY_INSTALL_PATH=${CLEW_3RDPARTY_INSTALL_PATH} \
	CLEW_MIMALLOC_ENABLE=${CLEW_MIMALLOC_ENABLE}

src_makeflags-y = \
	CLEW_LIBMAKEFILE_PATH=${CLEW_LIBMAKEFILE_PATH} \
	CLEW_3RDPARTY_PATH=${CLEW_3RDPARTY_PATH} \
	CLEW_3RDPARTY_INSTALL_PATH=${CLEW_3RDPARTY_INSTALL_PATH} \
	CLEW_MIMALLOC_ENABLE=${CLEW_MIMALLOC_ENABLE}

src_depends-y = \
	3rdparty

test_makeflags-y = \
	CLEW_LIBMAKEFILE_PATH=${CLEW_LIBMAKEFILE_PATH} \
	CLEW_3RDPARTY_PATH=${CLEW_3RDPARTY_PATH} \
	CLEW_3RDPARTY_INSTALL_PATH=${CLEW_3RDPARTY_INSTALL_PATH}

test_depends-y = \
	src

include ${CLEW_LIBMAKEFILE_PATH}/Makefile.lib
